version: '3'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "3000"
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5500"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
